{
 "title": "OLM - Optional Operator Detail",
 "time": { "from": "now-12h", "to": "now-6h" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"completed\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < (21 * 24 * 60 * 60))) + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"initial\"})) > (7 * 24 * 60 * 60))), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!~\"redhat.com|(^|.*\\\\.)ibm.com\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{support=~\"Premium|Standard\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+-0\\\\.nightly.+\"})) + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"}))"
   },
   {
    "name": "source_version",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.1\\\\.\\\\d+\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.2\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.3\\\\.\\\\d+.*\"})),  + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"completed\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < (21 * 24 * 60 * 60))) + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"initial\"})) > (7 * 24 * 60 * 60))), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+-0\\\\.nightly.+\"}))"
   },
   {
    "name": "operatorname",
    "label": "operator_name",
    "query": {
     "query": "query_result(sort_desc(count by(installed) (subscription_sync_total{installed!~\"packageserver.*\"})))"
    }
   },
   {
    "name": "operatorversion",
    "label": "operator_version",
    "query": {
     "query": "query_result(count by(installed) (subscription_sync_total{installed=~\"$operatorname.*\"}))"
    }
   },
   {
    "name": "csv_condition_state",
    "label": "csv_condition_state",
    "query": "RequirementsUnknown|AllRequirementsMet|InstallWaiting|InstallSucceeded|ComponentUnhealthy|BeingReplaced|Replaced|NeedsReinstall|NeedsCertRotation|APIServiceResourceIssue|APIServiceResourcesNeedReinstall|Copied|RequirementsNotMet|OwnerConflict|InstallComponentFailed|InvalidInstallStrategy|InstallCheckFailed|APIServiceInstallFailed|InvalidInstallModes|NoTargetNamespaces|UnsupportedOperatorGroup|NoOperatorGroup|TooManyOperatorGroups|InterOperatorGroupOwnerConflict|CannotModifyStaticOperatorGroupProvidedAPIs|UnsupportedWebhookRules|InstallComponentFailedNoRetry, RequirementsUnknown|AllRequirementsMet|InstallWaiting|InstallSucceeded|ComponentUnhealthy|BeingReplaced|Replaced|NeedsReinstall|NeedsCertRotation|APIServiceResourceIssue|APIServiceResourcesNeedReinstall|Copied, RequirementsNotMet|OwnerConflict|InstallComponentFailed|InvalidInstallStrategy|InstallCheckFailed|APIServiceInstallFailed|InvalidInstallModes|NoTargetNamespaces|UnsupportedOperatorGroup|NoOperatorGroup|TooManyOperatorGroups|InterOperatorGroupOwnerConflict|CannotModifyStaticOperatorGroupProvidedAPIs|UnsupportedWebhookRules|InstallComponentFailedNoRetry"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters running Operator",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "Clusters running Operator Versions",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc (count by (installed) (topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version)))"
    }
   ]
  },
  {
   "title": "Customers running Operator in more than 1 cluster",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count (count by (email_domain) (count by (_id, email_domain) (subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version + on (_id) group_left(email_domain) (0 * topk by (_id) (1, subscription_labels $source $source_version)))) > 1)"
    }
   ]
  },
  {
   "title": "Avg RAM (GiB) per Cluster Installed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(cluster:memory_usage_bytes:sum $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))) / (2^30)) \n/ \ncount(count by (_id) (cluster_version{type=\"completed\"} $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))))"
    }
   ]
  },
  {
   "title": "Avg CPU cores per Cluster Installed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))) \n/ \ncount(count by (_id) (cluster_version{type=\"completed\"} $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))))"
    }
   ]
  },
  {
   "title": "Avg Nodes per Cluster Installed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))) \n/ count(count by (_id) (cluster_version{type=\"completed\"} $source $source_version + on (_id) group_left(installed) (0 * topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))))"
    }
   ]
  },
  {
   "title": "Clusters install count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (_id) (subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version))",
     "legendFormat": "installed"
    }
   ]
  },
  { "title": "Installation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Channel breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (channel) (topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\",channel!=\"\"} $source $source_version))",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "OCP platform install count",
   "type": "grafana-piechart-panel",
   "description": "Cloud provider type and the installation method used.  Unknown cloud type is clusters older than 4.1.10, and unknown install type is clusters older than 4.1.8.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count by (cloud_type, type) \n((topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version\n+ on (_id) group_left(cloud_type) (topk by (_id) (1, 0 * label_replace(label_replace((cluster_infrastructure_provider $source $source_version) or label_replace(cluster_installer $source $source_version, \"type\", \"\", \"type\", \".*\"), \"type\", \"Unknown\", \"type\", \"\"), \"cloud_type\", \"$1\", \"type\", \"(.*)\")))\n+ on(_id) group_left(type) (topk by (_id) (1, label_replace(label_replace(cluster_installer $source $source_version, \"type\", \"UPI\", \"type\", \"(|other)\"), \"type\", \"IPI\", \"type\", \"openshift-install\")\n  or on (_id) label_replace(cluster_installer, \"type\", \"Unknown\", \"type\", \".*\")))))))",
     "legendFormat": "{{cloud_type}} ({{type}})"
    }
   ]
  },
  {
   "title": "OCP versions install count",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sort_desc((count by (version) (topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version + on (_id) group_left(version) (topk by (_id) (1, 0 * cluster_version{type=\"completed\"} $source $source_version))))))"
    }
   ]
  },
  {
   "title": "Install by Architecture",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sort_desc((count by (label_kubernetes_io_arch) (topk by (_id) (1, subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version + on (_id) group_left(label_kubernetes_io_arch) (topk by (_id) (1, 0 * node_role_os_version_machine:cpu_capacity_cores:sum $source $source_version))))))"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "README.md",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "\n### CSV Condition Reasons\n\nThe following table provides a short description of what the condition means:\n\n\n| **Condition Reason**                        | **Explanation for Telemetry**                                                                                                                              | **Operator is running**                 |\n| ------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |\n| RequirementsUnknown                         | OLM hasn't gotten around to checking for requirements yet                                                                                                  | no                                      |\n| RequirementsNotMet                          | One or more requirements to install haven't been met (crds, nativeapis, apis, serviceaccount, rbac)                                                        | no                                      |\n| AllRequirementsMet                          | The Operator is currently installing and all of its requirements have been met                                                                             | No (installing)                         |\n| OwnerConflict                               | Two operators own the same apis in the namespace, but are not connected via a chain of \"replaces\" (rare, mostly caused by a bug in 4.2)                    | no                                      |\n| InstallComponentFailed                      | Failed to create a component that makes up the Operator: deployment, CRD, RBAC apiservices, etc.                                                           | no                                      |\n| InvalidInstallStrategy                      | The install strategy for a csv is not in the format we expect.                                                                                             | no                                      | \n| InstallWaiting                              | Install is progressing and OLM is waiting for components to come online.                                                                                   | No (Installing)                         |\n| InstallSucceeded                            | The operator's deployments are all ready/available.                                                                                                        | yes                                     |\n| InstallCheckFailed                          | The operator never became healthy, OLM now treats the operator as failed.                                                                                  | no                                      |\n| ComponentUnhealthy                          | Some requirement or component is not in the state it should be, the Operator will be flipped back in an attempt to recreate anything that belongs to it.   | likely no                               |\n| BeingReplaced                               | Operator is being updated                                                                                                                                  | yes                                     |\n| Replaced                                    | Operator has been updated and newer version is healthy                                                                                                     | yes                                     |\n| NeedsReinstall                              | Operator configuration got updated ( subscription.config, rotating certs, proxy config, etc) and the Operator needs to be redeployed with the new settings | yes                                     |\n| NeedsCertRotation                           | The certs will be rotated for an apiservice-based operator.                                                                                                | yes                                     |\n| APIServiceResourceIssue                     | A previously created resource required to deploy an extension apiserver has disappeared.                                                                   | likely no                               |\n| APIServiceResourcesNeedReinstall            | Some resources required to run extension apiservers were not in the expected state, OLM will attempt to recreate them.                                     | likely no                               |\n| APIServiceInstallFailed                     | Extension apiserver install has failed in a way that OLM can't recover.                                                                                    | no                                      |\n| Copied                                      | This CSV is a placeholder to indicate the operator is watching the current namespace.                                                                      | Yes (depends on the parent, \"real\" csv) |\n| InvalidInstallModes                         | The CSV contains improperly formatted installmodes (duplicate entries, typos, etc)                                                                         | no                                      |\n| NoTargetNamespaces                          | There are no namespaces resolved as target namespaces for the current operatorgroup.                                                                       | no                                      |\n| UnsupportedOperatorGroup                    | The current operatorgroup does not support the installmodes of the Operator.                                                                               | no                                      |\n| NoOperatorGroup                             | Operator cannot be installed because the namespace does not have an OperatorGroup.                                                                         | no                                      |\n| TooManyOperatorGroups                       | We currently only allow 1 OperatorGroup per namespace.                                                                                                     | no                                      |\n| InterOperatorGroupOwnerConflict             | The operator provides an API that another operator provides in the current namespace (i.e. it is provided in an operatorgroup that targets this namespace) | no                                      |\n| CannotModifyStaticOperatorGroupProvidedAPIs | A CSV is present in an operatorgroup with \"static\" provided apis set and provides apis not in the set.                                                     |                                         |"
   }
  },
  {
   "title": "CSV condition states for Operator",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sort_desc(count by (reason) (csv_abnormal{name=~\"$operatorversion\", reason=~\"$csv_condition_state.*\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "Top 50 customers using Operator",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "topk (50, sort_desc (count by (email_domain) (subscription_sync_total{installed=~\"$operatorversion\"} $source $source_version + on (_id) group_left(email_domain) (0 * topk by (_id) (1, subscription_labels $source $source_version)))))"
    }
   ]
  },
  {
   "title": "Cluster IDs where Operator is installed",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "count by (_id) \r\n(\r\n(count by (_id,name) (csv_succeeded{name=~\"$operatorversion\"}>0 $source $source_version)) unless\r\n\r\n(count by (_id,name) (csv_abnormal{name=~\"$operatorversion\", reason=~\"Replaced|BeingReplaced\"}))\r\n)"
    }
   ]
  }
 ]
}