{
 "title": "Optional Resource Detail",
 "time": { "from": "now-78h", "to": "now-6h" },
 "templating": {
  "list": [
   {
    "name": "resource",
    "query": {
     "query": "query_result(topk(500, sum by(resource) (cluster:usage:resources:sum{resource!~\".*\\\\.openshift\\\\.io|.*\\\\.k8s\\\\.io|.*\\\\.coreos.com|.*\\\\.metal3\\\\.io|.*\\\\.cni\\\\.cncf\\\\.io|.*\\\\.apps|.*\\\\.autoscaling|.*\\\\.batch|.*\\\\.policy|[^\\\\.]+\"})))"
    }
   },
   {
    "name": "source",
    "query": "all : *1, external : * on(_id) group_left(_blah) group by(_id) (id_version_ebs_account_internal:cluster_subscribed{internal=\"\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Total count across all clusters",
   "type": "stat",
   "description": "Sum of resource counts for this resource across all clusters",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "Total resource counts over time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:usage:resources:sum{resource=\"${resource}\"} $source)",
     "legendFormat": "${resource}"
    }
   ]
  },
  {
   "title": "Max count in any cluster",
   "type": "stat",
   "description": "Maximum number of this resource found in any cluster",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "Average count per cluster",
   "type": "stat",
   "description": "Average count of this resource across all clusters",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "Median count per cluster",
   "type": "stat",
   "description": "Median count of this resource across all clusters",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.50, cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "75th quantile count per cluster",
   "type": "stat",
   "description": "75% of clusters have this many or fewer of this resource in the cluster",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.75, cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "90th quantile count per cluster",
   "type": "stat",
   "description": "90% of clusters have this many or fewer of this resource in the cluster",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.90, cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  },
  {
   "title": "95th quantile count per cluster",
   "type": "stat",
   "description": "95% of clusters have this many or fewer of this resource in the cluster",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, cluster:usage:resources:sum{resource=\"${resource}\"} $source)"
    }
   ]
  }
 ]
}